# Generated by Django 3.1.5 on 2021-01-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reipe',
            new_name='Recipe',
        ),
    ]
